### PR TITLE
gfortran support - initial commit for review

### PR DESCRIPTION
**Pull request by steabert**
Hi,

this is a concept of how to add gfortran support to linter-gcc. I first tried to use linter-gfortran but that was so uncustomizable that I then decided to hack this linter-gcc to support gfortran as well. It works quite well so far for me, but since I have no javascript experience at all, most of this was copy-pasting and trial and error. So, this needs a thorough review. I must note that I have language-fortran installed for the tests.

Any feedback would be nice, especially:
- you think it is acceptable to add gfortran support to linter-gcc
- there are parts that need serious reworking

Steven

### CODE REVIEW

**Comment by hebaishi** [comment]
I don't think this is the best way forward, because:
1. Calling it ```linter-gcc``` is misleading for ```gfortran``` users.
2. Adding ```gfortran``` support to ```linter-gcc``` is possible, but it's messy.

Here's what I suggest:
1. I create a **generic** linter, that has all the features of linter-gcc, but with **generic** options.
2. Create a template file with instructions on how to customize the linter for your compiler of choice. This means people will be able to create a linter with all the basic linter-gcc features, but customized for their compiler.

I will try and get this generic linter done tonight, with Travis CI tests and everything. What do you think?

**Comment by steabert** [comment]
Well, any solution that results in a good gfortran linter that can be used without much hassle is fine with me.

As you mentioned, this was indeed rather messy. On the other hand, I was myself surprised that linter-gcc uses g++, and I thought since gfortran is part of the GCC software, adding it would be logical...

If you can create a generic linter, I would certainly try my best to adapt it for use with gfortran. But I'm not sure if I fully understand what you mean with template file. For example, if the next person comes along that would like to use a gfortran linter, would they have to figure out the regex to use to parse the error messages? Or will the generic linter come with default templates for a variety of compilers (gcc/g++/gfortran)?

Anyway, thanks a lot for caring about this :)

**Comment by hebaishi** [comment]
Firstly, yes you're right about fortran being in the GNU Compiler Collection, but what I mean here is does it really make sense to write a linter for both C/C++ and fortran? These are very different languages and combining them into one linter is definitely going to be messy. If it's not messy now, it will become messy in the future, when we might want to add features specific to each language.

Secondly, yes I mean providing the user with a base where most of the code has already been written. I think initially, I will include the regex for matching the errors/warnings of ```g++/gcc```. The user can modify this regex for other compilers.

So the repo would contain a file called ```instructions.md``` with instructions like these:
1. Modify functionA to specify valid grammars for your linter.
2. Modify regex in fileA to capture errors/warnings
3. Modify the linter configuration options in fileB
etc.

**Comment by steabert** [comment]
I agree on your first point, probably this would lead to more mess in the future when trying to support languange/compiler-specific features.

OK, so, if your generic linter is ready, I'll be happy to try it out!

**Pull request closed without merging**
